spin_manifest_version = "1"
authors = ["Chris Matteson <chris.matteson@gmail.com>"]
description = "Spin AI Reading Assistant"
name = "Read With AI"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[variables]
openai_key = { default = "kv" }
auth_token = { default = "kv" }

[[component]]
id = "list"
source = "list/target/list.wasm"
exclude_files = ["**/node_modules"]
key_value_stores = ["default"]
sqlite_databases = ["default"]
[component.trigger]
route = "/api/list"
[component.build]
command = "npm run build"
workdir = "list"

[[component]]
id = "write"
source = "write/target/write.wasm"
exclude_files = ["**/node_modules"]
key_value_stores = ["default"]
sqlite_databases = ["default"]
ai_models = ["llama2-chat", "all-minilm-l6-v2"]
[component.config]
openai_key = "{{ openai_key }}"
auth_token = "{{ auth_token }}"
[component.trigger]
route = "/api/write"
[component.build]
command = "npm run build"
workdir = "write"

[[component]]
id = "read"
source = "read/target/read.wasm"
exclude_files = ["**/node_modules"]
key_value_stores = ["default"]
sqlite_databases = ["default"]
[component.trigger]
route = "/api/read"
[component.build]
command = "npm run build"
workdir = "read"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "ui"
files = [ { source = "ui/dist", destination = "/" } ]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
workdir = "ui"

[[component]]
source = { url = "https://github.com/radu-matei/spin-kv-explorer/releases/download/v0.9.0/spin-kv-explorer.wasm", digest = "sha256:07f5f0b8514c14ae5830af0f21674fd28befee33cd7ca58bc0a68103829f2f9c" }
id = "kv-explorer"
# add or remove stores you want to explore here
key_value_stores = ["default"]
[component.trigger]
route = "/internal/kv-explorer/..."

[[component]]
id = "chat"
source = "chat/target/chat.wasm"
ai_models = ["llama2-chat", "all-minilm-l6-v2"]
[component.trigger]
route = "/api/chat"
[component.build]
command = "npm run build"
workdir = "chat"

[[component]]
id = "upload"
source = "upload/target/upload.wasm"
key_value_stores = ["default"]
[component.trigger]
route = "/upload/..."
[component.build]
command = "npm run build"
workdir = "upload"

